
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CBRACE = 22;
  public static final int LTE = 13;
  public static final int OVER = 35;
  public static final int SLASH = 11;
  public static final int SEMI = 19;
  public static final int REPEAT = 31;
  public static final int OBRACK = 23;
  public static final int INT = 4;
  public static final int MINUS = 9;
  public static final int OBRACE = 21;
  public static final int WRITE = 34;
  public static final int STAR = 10;
  public static final int OCOMMENT = 27;
  public static final int LT = 12;
  public static final int COMMA = 20;
  public static final int CCOMMENT = 28;
  public static final int UNTIL = 32;
  public static final int NUM = 37;
  public static final int PLUS = 8;
  public static final int ASSIGN = 18;
  public static final int IF = 3;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int CPAREN = 26;
  public static final int error = 1;
  public static final int VOID = 6;
  public static final int EQ = 16;
  public static final int ERROR = 38;
  public static final int GTE = 15;
  public static final int ELSE = 2;
  public static final int OPAREN = 25;
  public static final int READ = 33;
  public static final int WHILE = 7;
  public static final int THEN = 29;
  public static final int NE = 17;
  public static final int END = 30;
  public static final int GT = 14;
  public static final int CBRACK = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "EQ",
  "NE",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "OBRACE",
  "CBRACE",
  "OBRACK",
  "CBRACK",
  "OPAREN",
  "CPAREN",
  "OCOMMENT",
  "CCOMMENT",
  "THEN",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "OVER",
  "ID",
  "NUM",
  "ERROR"
  };
}

